import { EnemyDef, EnemyKind } from './types';

export const ENEMIES: Record<EnemyKind, EnemyDef> = {
  drone: {
    kind: 'drone',
    name: 'Swarm Drone',
    hp: 35,
    speed: 1.6,
    armor: 0,
    bounty: 6,
    damage: 1,
    color: 'rose',
    glyph: 'd',
  },
  walker: {
    kind: 'walker',
    name: 'Armored Walker',
    hp: 140,
    speed: 0.85,
    armor: 6,
    bounty: 14,
    damage: 2,
    color: 'orange',
    glyph: 'W',
  },
  shielded: {
    kind: 'shielded',
    name: 'Shielded Trooper',
    hp: 70,
    speed: 1.1,
    armor: 2,
    shield: 60,
    bounty: 12,
    damage: 2,
    color: 'sky',
    glyph: 'S',
  },
  stealth: {
    kind: 'stealth',
    name: 'Stealth Infiltrator',
    hp: 55,
    speed: 1.4,
    armor: 0,
    bounty: 16,
    damage: 3,
    stealth: true,
    color: 'violet',
    glyph: 'X',
  },
  boss: {
    kind: 'boss',
    name: 'Siege Mech',
    hp: 1500,
    speed: 0.55,
    armor: 12,
    shield: 300,
    bounty: 350,
    damage: 25,
    color: 'red',
    glyph: 'Ω',
  },
  runner: {
    kind: 'runner',
    name: 'Sprint Drone',
    hp: 22,
    speed: 2.7,
    armor: 0,
    bounty: 7,
    damage: 2,
    color: 'lime',
    glyph: 'r',
  },
  brute: {
    kind: 'brute',
    name: 'Siege Brute',
    hp: 620,
    speed: 0.6,
    armor: 10,
    bounty: 55,
    damage: 8,
    color: 'orange',
    glyph: 'B',
  },
  flyer: {
    kind: 'flyer',
    name: 'Gunship',
    hp: 90,
    speed: 1.5,
    armor: 0,
    bounty: 18,
    damage: 4,
    flying: true,
    color: 'fuchsia',
    glyph: 'V',
  },
  healer: {
    kind: 'healer',
    name: 'Mender',
    hp: 130,
    speed: 1.0,
    armor: 2,
    bounty: 26,
    damage: 3,
    heal: { radius: 2.2, perSec: 14 },
    color: 'emerald',
    glyph: 'H',
  },
  splitter: {
    kind: 'splitter',
    name: 'Splitter',
    hp: 160,
    speed: 0.95,
    armor: 2,
    bounty: 20,
    damage: 4,
    splitInto: { kind: 'runner', count: 3 },
    color: 'yellow',
    glyph: 'Y',
  },
};

export const ENEMY_LIST = Object.values(ENEMIES);
export const ENEMY_KINDS = Object.keys(ENEMIES) as EnemyKind[];
